apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow
  namespace: baserow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baserow 
  template:
    metadata:
      labels:
        app: baserow 
    spec:
      containers:
      - name: baserow
        image: baserow/baserow:1.27.2 
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: baserow-data
          mountPath: /baserow/data
        env:
        - name: BASEROW_PUBLIC_URL
          value: "https://baserow.koden.bzh"
      volumes:
      - name: baserow-data
        persistentVolumeClaim:
          claimName: baserow-data-pvc
