apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baserow-ingress
  namespace: baserow
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true" 
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - baserow.koden.bzh
    secretName: baserow-tls
  rules:
  - host: baserow.koden.bzh 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: baserow-service
            port:
              number: 80