apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baserow-data-pvc
  namespace: baserow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-cinder-classic