
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: baserow
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: baserow-secret
                  key: REDIS_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: baserow
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
