apiVersion: v1
kind: Secret
metadata:
  name: baserow-secret
  namespace: baserow
type: Opaque
data:
  # Encodez les valeurs en base64, par exemple: echo -n "yourpassword" | base64
  BASEROW_DATABASE_PASSWORD: <base64-encoded-password>
  BASEROW_SECRET_KEY: <base64-encoded-secret-key>